OBJS = semafor.o komunikat.o pamiec.o
HDRS = semafor.h komunikat.h pamiec.h params.h

all: start pasazer kapitan dyspozytor odprawa kontrola_osobista

start: start.o $(OBJS)
	gcc -o start start.o $(OBJS)
start.o: start.c $(HDRS)
	gcc -c start.c

pasazer: pasazer.o $(OBJS)
	gcc -o pasazer pasazer.o $(OBJS)
pasazer.o: pasazer.c $(HDRS)
	gcc -c pasazer.c

kapitan: kapitan.o $(OBJS)
	gcc -o kapitan kapitan.o $(OBJS)
kapitan.o: kapitan.c $(HDRS)
	gcc -c kapitan.c

dyspozytor: dyspozytor.o $(OBJS)
	gcc -o dyspozytor dyspozytor.o $(OBJS)
dyspozytor.o: dyspozytor.c $(HDRS)
	gcc -c dyspozytor.c

odprawa: odprawa.o $(OBJS)
	gcc -o odprawa odprawa.o $(OBJS)
odprawa.o: odprawa.c $(HDRS)
	gcc -c odprawa.c

kontrola_osobista: kontrola_osobista.o $(OBJS)
	gcc -o kontrola_osobista kontrola_osobista.o $(OBJS)
kontrola_osobista.o: kontrola_osobista.c $(HDRS)
	gcc -c kontrola_osobista.c

semafor.o: semafor.c
	gcc -c semafor.c
komunikat.o: komunikat.c
	gcc -c komunikat.c
pamiec.o: pamiec.c
	gcc -c pamiec.c

lunch:
	./start

clear:
	rm -v *.o
